workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Create android
        script: |
          flutter create . --platforms=android
      - name: Get packages
        script: |
          flutter pub get
      - name: Build Release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
