dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.2
  provider: ^6.1.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1  camera: ^0.10.5+9
  permission_handler: ^11.3.1
