import 'package:flutter/material.dart';
const String POCHI="0180879250";
void main(){runApp(SawaTokApp());}
class SawaTokApp extends StatelessWidget{@override Widget build(BuildContext c){return MaterialApp(debugShowCheckedModeBanner:false, home:HomePage());}}
class HomePage extends StatefulWidget{@override _HomePageState createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{
int idx=0;
int balance=1250;
TextEditingController amt=TextEditingController();
void withdraw(){int a=int.tryParse(amt.text)??0; if(a<100||a>balance){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Min 100 Max $balance"))); return;} setState(()=>balance-=a); showDialog(context:context, builder:(_)=>AlertDialog(title:Text("Success"), content:Text("KSH $a imetumwa Pochi $POCHI"), actions:[TextButton(onPressed:()=>Navigator.pop(context), child:Text("Sawa"))]));}
Widget forYou(){return Container(color:Colors.black, child:Center(child:Column(mainAxisSize:MainAxisSize.min, children:[Text("VIDEO DEMO", style:TextStyle(color:Colors.white, fontSize:22)), SizedBox(height:20), ElevatedButton(onPressed:(){int my=(100*0.3).toInt(); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Gift 100 - Yako KSH $my, Creator 70")));}, child:Text("Tuma Gift 100 - 30% Yako"))])));}
Widget live(){return Container(color:Colors.black, child:Center(child:Text("LIVE - Coming Soon", style:TextStyle(color:Colors.white))));}
Widget wallet(){return Scaffold(backgroundColor:Colors.black, body:Padding(padding:EdgeInsets.all(16), child:Column(children:[SizedBox(height:40), Icon(Icons.wallet, size:60, color:Colors.green), Text("KSH $balance", style:TextStyle(color:Colors.white, fontSize:32, fontWeight:FontWeight.bold)), Text("30% Yako - 70% Creator", style:TextStyle(color:Colors.green)), Text("Pochi: $POCHI", style:TextStyle(color:Colors.white70)), SizedBox(height:20), TextField(controller:amt, keyboardType:TextInputType.number, style:TextStyle(color:Colors.white), decoration:InputDecoration(hintText:"Amount min 100", hintStyle:TextStyle(color:Colors.grey), filled:true, fillColor:Color(0xFF222222), border:OutlineInputBorder(borderRadius:BorderRadius.circular(10)))), SizedBox(height:15), SizedBox(width:double.infinity, height:50, child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Colors.green), onPressed:withdraw, child:Text("WITHDRAW VIA M-PESA", style:TextStyle(fontWeight:FontWeight.bold)))), Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly, children:[TextButton(onPressed:()=>setState(()=>amt.text="100"), child:Text("100")), TextButton(onPressed:()=>setState(()=>amt.text="500"), child:Text("500")), TextButton(onPressed:()=>setState(()=>amt.text="$balance"), child:Text("ALL"))])])));}
@override Widget build(BuildContext context){return Scaffold(body:[forYou(), live(), wallet()][idx], bottomNavigationBar:BottomNavigationBar(currentIndex:idx, onTap:(i)=>setState(()=>idx=i), items:[BottomNavigationBarItem(icon:Icon(Icons.home), label:"For You"), BottomNavigationBarItem(icon:Icon(Icons.live_tv), label:"Live"), BottomNavigationBarItem(icon:Icon(Icons.wallet), label:"Wallet")]));}
}
